version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: "book_shop"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - /home/username/pgdata:/var/lib/postgresql/data